### PR TITLE
Make textures load without warnings

### LINKED ISSUE #175: THREE.WebGLRenderer: Texture marked for update but image is incomplete
I suspect that somehow we miss an async call in our code - which does not matter on fast machines but fails on my slower machine. Thats why I see tons of those warnings as defined in the title.

Code of threejs that produces this warning is here:

```
	function setTexture2D( texture, slot ) {

		var textureProperties = properties.get( texture );

		if ( texture.isVideoTexture ) updateVideoTexture( texture );

		if ( texture.version > 0 && textureProperties.__version !== texture.version ) {

			var image = texture.image;

			if ( image === undefined ) {

				console.warn( 'THREE.WebGLRenderer: Texture marked for update but image is undefined' );

			} else if ( image.complete === false ) {

				console.warn( 'THREE.WebGLRenderer: Texture marked for update but image is incomplete' );

			} else {

				uploadTexture( textureProperties, texture, slot );
				return;

			}

		}

		state.activeTexture( 33984 + slot );
		state.bindTexture( 3553, textureProperties.__webglTexture );

	}
```

It's not reliable reproducible - a fresh build (uncached?) seldom shows the error, a reload of the cached table most of the time.

### PR DESCRIPTION
**Pull request by neophob**
Make sure loadLdrTexture returns only if image has been loaded, this was not the case and could work or not.

I also removed some unneeded promises.

Using this branch I was not able to trigger the issue again. 

Note: before it worked as well, but loading time was higher if we picked up the "bad path" (see description in #175) and we already draw the playfield black (only lamps were visible), then after some seconds the playfield appeared.

The lightning issue is still not fixed, will address this in a separate PR

### CODE REVIEW

File: lib/render/threejs/three-texture-loader-browser.ts [hunk 1]
```diff
@@ -84,14 +84,18 @@ async function load(mimeType: string, objectUrl: string): Promise<ThreeTexture>
...
 	}
-	return Promise.resolve(loadLdrTexture(objectUrl));
+	return loadLdrTexture(objectUrl);
 }
 
-function loadLdrTexture(objectUrl: string): ThreeTexture {
-	const texture = new ThreeTexture();
-	texture.image = new Image();
-	texture.image.src = objectUrl;
-	return texture;
```
Comment (neophob) [inline lib/render/threejs/three-texture-loader-browser.ts]: about your comment
>three will know when it's loaded and handle it at that point
in theory yes, there are two points against it:

- its a warning and should be avoided if possible (our app does a lot when bootstrapping - so lets use a promise and don't let threejs wait in a busy loop polling until the image arrives)
- i see more than 9000 lines of exact the same log message when this error happens (the exported console log is more than 13MB) - which makes not really fun debugging ;)

File: lib/render/threejs/three-texture-loader-browser.ts [hunk 2]
```diff
@@ -84,14 +84,18 @@ async function load(mimeType: string, objectUrl: string): Promise<ThreeTexture>
 	if (mimeType === 'application/octet-stream') {
 		return await loadHdrTexture(objectUrl);
```
Comment (neophob) [inline lib/render/threejs/three-texture-loader-browser.ts]: not sure, but this wait could be removed as well, right?

Comment (freezy) [reply lib/render/threejs/three-texture-loader-browser.ts]: Yes. Actually I think I've changed the way textures are loaded a few weeks back but didn't adapt all the method signatures. Might be possible to make more methods sync.

File: lib/render/threejs/three-texture-loader-browser.ts (hunk 1 above)
Comment (freezy) [reply lib/render/threejs/three-texture-loader-browser.ts]: Fair enough. I admit I haven't tested the other way, if you're saying this doesn't come with a performance hit, I'm fine with it.

Comment (neophob) [reply lib/render/threejs/three-texture-loader-browser.ts]: jep - never saw this on my beefy machine but on my aging home notebook

File: lib/render/threejs/three-texture-loader-browser.ts (hunk 2 above)
Comment (neophob) [reply lib/render/threejs/three-texture-loader-browser.ts]: removed it, think we can improve that later
